### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by vklachkov** [thebehera/mqtt#65]
Hello! 

I want to work with you to get the project to the production level. My mqtt client use Paho MQQT library, but its problems prevent from developing my application. 

How to start? I built the library with the update to Kotlin 1.4.30. How do I run all available tests? There is an example of an android app using the library? Where is some docs for writing clients?

I'm not the only one dissatisfied with the quality of the existing solution. Your library is very much needed not only by me

**Comment by mochadwi** [comment]
Would love to see the updates ❤️

**Comment by thebehera** [comment]
Hey guys! I love that you are still interested in the project.

My father and I have had a lot of things come up in life (thankfully we are fully healthy and safe, no covid issues ❤️)
It's been a few months since i've touched this project but i'll provide better updates soon. Give me a few weeks?

**Comment by thebehera** [comment]
I don't have a good collaboration plan just yet but that's what i'll work on!

**Comment by zgdump** [comment]
Hi, @thebehera. I am very glad to see your health and return, we will wait for your plan!

For so much time, priorities have changed and I have left Android development, but I am still interested in the library and will take part in the development)

**Comment by thebehera** [comment]
This project has been moved to https://github.com/ditchoom/mqtt ! It works currently on several platforms. Stay tuned there for updates!
